"""
Telecom Churn End-to-End Pipeline

Workflow:
    Source Files (Excel)
            ↓
    PySpark ETL Processing
            ↓
    Silver Parquet Layer
            ↓
    BigQuery Staging Layer
            ↓
    dbt Cloud Transformations
            ↓
    Data Quality Validation
            ↓
    Pipeline Completion
"""

from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator
from airflow.operators.empty import EmptyOperator

from datetime import datetime, timedelta
import os
import requests

from google.cloud import bigquery
from google.oauth2 import service_account
import pyarrow.parquet as pq


# ==================================================
# DEFAULT DAG CONFIGURATION
# ==================================================

default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "retries": 1,
    "retry_delay": timedelta(minutes=5),
}


# ==================================================
# PROJECT CONFIGURATION
# ==================================================

CREDENTIALS_PATH = (
    "/opt/airflow/credentials/"
    "telecom-churn-50111-44ee679c90b7.json"
)

PROJECT_ID = "telecom-churn-50111"

DATASET = "telecom_churn_airflow_test"

STAGING_TABLE = (
    f"{PROJECT_ID}.{DATASET}.stg_silver_telecom_test"
)

PARQUET_PATH = "/opt/airflow/data/silver/telecom"


# ==================================================
# TASK FUNCTIONS
# ==================================================
# 1. Load Silver Parquet data into BigQuery staging
# 2. Trigger dbt Cloud transformation job
# 3. Validate staging layer row count
# ==================================================


def load_silver_to_bigquery():
    """
    Load the Silver Parquet dataset generated by
    PySpark into a BigQuery staging table.
    """

    credentials = (
        service_account.Credentials
        .from_service_account_file(CREDENTIALS_PATH)
    )

    client = bigquery.Client(
        credentials=credentials,
        project=PROJECT_ID,
    )

    print("Reading Silver Parquet dataset...")

    parquet_table = pq.read_table(PARQUET_PATH)

    df = parquet_table.to_pandas()

    print(f"Rows loaded from parquet: {len(df)}")

    job_config = bigquery.LoadJobConfig(
        write_disposition="WRITE_TRUNCATE",
        autodetect=True,
    )

    load_job = client.load_table_from_dataframe(
        df,
        STAGING_TABLE,
        job_config=job_config,
    )

    load_job.result()

    table_info = client.get_table(STAGING_TABLE)

    print(
        f"Loaded {table_info.num_rows} rows "
        f"into {STAGING_TABLE}"
    )


def trigger_dbt_cloud():
    """
    Trigger a dbt Cloud job using the dbt REST API.
    """

    api_token = os.environ["DBT_API_TOKEN"]
    account_id = os.environ["DBT_ACCOUNT_ID"]
    job_id = os.environ["DBT_JOB_ID"]

    url = (
        f"https://hi944.us1.dbt.com/api/v2/"
        f"accounts/{account_id}/jobs/{job_id}/run/"
    )

    headers = {
        "Authorization": f"Token {api_token}",
        "Content-Type": "application/json",
    }

    payload = {
        "cause": "Triggered by Airflow telecom_churn_pipeline"
    }

    response = requests.post(
        url,
        headers=headers,
        json=payload,
        timeout=60,
    )

    if response.status_code not in [200, 201]:
        raise Exception(
            f"dbt API error: "
            f"{response.status_code} "
            f"{response.text}"
        )

    run_id = (
        response.json()
        .get("data", {})
        .get("id")
    )

    print(
        f"dbt Cloud job triggered successfully. "
        f"Run ID: {run_id}"
    )


def data_quality_check():
    """
    Validate that the staging table contains data
    before marking the pipeline as successful.
    """

    credentials = (
        service_account.Credentials
        .from_service_account_file(CREDENTIALS_PATH)
    )

    client = bigquery.Client(
        credentials=credentials,
        project=PROJECT_ID,
    )

    query = f"""
    SELECT COUNT(*) AS row_count
    FROM `{STAGING_TABLE}`
    """

    result = client.query(query).result()

    row_count = next(result).row_count

    print(f"Staging table row count: {row_count}")

    if row_count == 0:
        raise ValueError(
            "Data quality check failed. "
            "Table contains 0 rows."
        )

    print("Data quality check passed.")


# ==================================================
# DAG DEFINITION
# ==================================================

with DAG(
    dag_id="telecom_churn_orchestration",
    description="Telecom Churn End-to-End Pipeline",
    default_args=default_args,
    start_date=datetime(2025, 1, 1),
    schedule="@daily",
    catchup=False,
    tags=[
        "telecom",
        "pyspark",
        "bigquery",
        "dbt",
    ],
) as dag:

    start = EmptyOperator(
        task_id="start"
    )

    validate_source_files = BashOperator(
        task_id="validate_source_files",
        bash_command="""
        test -f /opt/airflow/data/input/Client.xlsx &&
        test -f /opt/airflow/data/input/Record.xlsx
        """
    )

    run_pyspark_etl = BashOperator(
        task_id="run_pyspark_etl",
        bash_command="""
        python /opt/airflow/scripts/telecom_etl.py
        """,
        execution_timeout=timedelta(hours=2),
    )

    load_bigquery_staging = PythonOperator(
        task_id="load_bigquery_staging",
        python_callable=load_silver_to_bigquery,
    )

    trigger_dbt_cloud_task = PythonOperator(
        task_id="trigger_dbt_cloud",
        python_callable=trigger_dbt_cloud,
    )

    data_quality_check_task = PythonOperator(
        task_id="data_quality_check",
        python_callable=data_quality_check,
    )

    end = EmptyOperator(
        task_id="end"
    )

    (
        start
        >> validate_source_files
        >> run_pyspark_etl
        >> load_bigquery_staging
        >> trigger_dbt_cloud_task
        >> data_quality_check_task
        >> end
    )