version: 2

sources:
  - name: telecom
    database: telecom-churn-50111
    schema: telecom_churn_data_set

    tables:
      - name: stg_silver_telecom
      - name: stg_usage_events
      - name: stg_network_events
      - name: stg_customer_care_calls
      - name: stg_churn_risk